### ISSUE TITLE
Intermittently breaks steam overlay

### ISSUE THREAD

**Issue by DannBoMambo** [milleroski/HoldScanButton#2]
It was very difficult to pin this issue down, but with a lot of testing we narrowed a steam overlay bug down to this mod. 

Whenever this mod is enabled for us, there's a good chance the steam overlay will be bugged out, as if the resolution were increased dramatically, and then you can't close it, and any attempts to relaunch the game will result in the same issue until steam is restarted or the mod is disabled. It doesn't happen every time but once it starts that's the only solution. Disabling other mods has no effect, and reenabling this one reintroduces the issue.

Other users in steam discussions have mentioned having the same issue with this mod. Nothing that I can see shows up in the BepInEx mod related to it but I'm also not knowledgeable enough to know what to look for.

**Comment by milleroski** [comment]
I have absolutely no idea what would be causing this issue, my mod has absolutely nothing to do with the steam overlay. I'll try to look into it. Thank you for reporting this!

**Comment by DannBoMambo** [comment]
The issue popped up again with the mod disabled so I'm not sure what to make of it. Will need to troubleshoot further but it might not be this mod causing it, at least not in isolation. I'll let you know if we find anything further out.

**Comment by milleroski** [comment]
I've heard of the Steam overlay sometimes sometimes bugging out due to the BepInEx console being enabled. You could try disabling it by going into BepInEx.cfg and setting Enabled to false under Logging.Console. You can find it in the BepInEx/config folder, or just use the Thunderstore / r2modman config editor.
